ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS text_extracted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS file_hash TEXT,
  ADD COLUMN IF NOT EXISTS total_tokens INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chunk_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avg_chunk_size INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS quality_status TEXT,
  ADD COLUMN IF NOT EXISTS quality_message TEXT;

CREATE INDEX IF NOT EXISTS idx_documents_file_hash ON documents(file_hash);
